### PR TITLE
Add support for running tests on native ios app

### PR DESCRIPTION
**Pull request by ndmanvar**
Also added in test that adds 4 Plant Moods to cart + Clicks on cart + clicks on purchase

### CODE REVIEW

**Comment by ndmanvar** [comment]
Succesful test in Saucelabs -> https://app.saucelabs.com/tests/a71503e7b43b41ff82f144777d751a0b

**Comment by ndmanvar** [comment]
Transactions from one test run -> https://sentry.io/organizations/testorg-az/discover/results/?end=2022-06-29T04%3A30%3A56&field=transaction&field=project&field=count%28%29&field=avg%28transaction.duration%29&field=p75%28%29&field=p95%28%29&name=Transactions+by+Volume&project=6249899&query=event.type%3Atransaction&sort=-count&start=2022-06-29T04%3A28%3A58&yAxis=count%28%29

**Comment by ndmanvar** [comment]
Looks like device is reporting incorrectly (running on iphone11 simulator)
image
We can figure that out later

**Comment by ndmanvar** [comment]
@thinkocapo + @cstavitsky , feel free to review/feedback.
we can merge this in and we'll start getting some ios transactions (via automation).

**Comment by thinkocapo** [comment]
I checked the traces for each transaction. I don't see a backend transaction that corresponds to purchase, but I'm also not seeing it for when I was running this myself in Xcode a week or two ago. I'm looking into it. @ndmanvar

**Comment by thinkocapo** [comment]
It looks like the iOS Custom Transaction is not getting traced to the right backend transaction /checkout endpoint in Flask.

Instead, it's getting the same traceId as an earlier trace, which was the home screen EmpowerPlantViewController.

Looks like it's this problem happening, https://github.com/getsentry/sentry-cocoa/issues/1827

**Comment by ndmanvar** [comment]
@thinkocapo - looks like we're not seeing the right/exact data we want (as you outlined above), but I think it would still be worth merging this so we can start arming folks with iOS mobile web vitals + screen load transactions + etc.

**Comment by ndmanvar** [comment]
any feedback re. the tests / code in this PR?

**Comment by thinkocapo** [comment]
@ndmanvar it looked good to me but @cstavitsky asked me some questions about if this is good to go, start running it. Chris could you ask your questions her?

**Review by thinkocapo — APPROVED** [review]

**Review by cstavitsky — APPROVED** [review]
@thinkocapo took a closer look, my questions are answered

**Comment by thinkocapo** [comment]
@ndmanvar here's the error that got produced from TDA running on the Release 0.0.2 which got uploaded Aug9th

symbolicated correctly

[event link](https://sentry.io/organizations/testorg-az/discover/ios:dc4b0a4c9d344e25a5336c640e0137f9/?end=2022-08-11T11%3A59%3A00.000&field=title&field=event.type&field=project&field=user.display&field=se&field=timestamp&name=All+Events&project=6249899&query=%21se%3Areplay&sort=-timestamp&start=2022-08-11T11%3A46%3A40.000&widths=518&yAxis=count%28%29)
image

**Pull request merged**
