### PR TITLE
Upgrade node sdk to 7.41 + enable stack locals

### PR DESCRIPTION
**Pull request by ndmanvar**
From staging:

image
https://testorg-az.sentry.io/issues/3827876991/events/cd16b21a3c3643128a85b1b8b1e6665b/?project=4504330844635136#exception

### CODE REVIEW

**Comment by ndmanvar** [comment]
docs -> https://docs.sentry.io/platforms/node/guides/connect/configuration/integrations/default-integrations/#localvariables

**Comment by ndmanvar** [comment]
once merged, i can then deploy to `production`

**Comment by ndmanvar** [comment]
@realkosty - can you review+appropve when you get a chance?

**Comment by ndmanvar** [comment]
[would love to get this into prod today and mark it as done], leaving only profiling as TODO/WIP on express]

**Review by realkosty — APPROVED** [review]

**Comment by ndmanvar** [comment]
deployed
works in prod ✅ 
image

**Pull request merged**
